name: Sync to GitLab

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v2

      - name: Trigger GitLab CI/CD pipeline
        env:
          GITLAB_TRIGGER_TOKEN: ${{ secrets.GITLAB_TRIGGER_TOKEN }}
        run: |
          curl --request POST \
            --form "token=$GITLAB_TRIGGER_TOKEN" \
            --form "ref=main" \
            https://gricad-gitlab.univ-grenoble-alpes.fr/api/v4/projects/34171/trigger/pipeline

